#!/usr/bin/bash

if [[ "$1" == "common" ]]; then
  echo "git pull : common (project_common)"
  cd $ACSL_WORK_DIR/common
  git pull
  pip install -e . 2>/dev/null || pip install . 2>/dev/null
elif [[ -n "$1" ]]; then
  echo "git pull : $1"
  cd $ACSL_WORK_DIR/$1
  git pull
else
  echo "git pull : $PROJECT (+ submodules)"
  cd $ACSL_WORK_DIR
  git pull --recurse-submodules
  git submodule update --init --recursive
fi
